/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_beifengtz_jvmm_core_OsProvider */

#ifndef _Included_org_beifengtz_jvmm_core_OsProvider
#define _Included_org_beifengtz_jvmm_core_OsProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_beifengtz_jvmm_core_OsProvider
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_beifengtz_jvmm_core_OsProvider_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     org_beifengtz_jvmm_core_OsProvider
 * Method:    load
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_beifengtz_jvmm_core_OsProvider_load
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
