{
 "title": "Jvmm-JVM Dashboard",
 "description": "Jvmm grafana dashboard for JVM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node_query", "label": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "{{vm_version}}"
    }
   ]
  },
  {
   "title": "JVM CPU Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p_cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_mem_heap_used_percent{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_mem_heap_used{node=\"$node_query\"} + jvm_mem_nonheap_used{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(jvm_loaded_class_total{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "total loaded class"
    },
    {
     "expr": "increase(jvm_loaded_class{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "loaded class"
    },
    {
     "expr": "increase(jvm_unloaded_class{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "unloaded class"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "jvm_thread_deadlocked{node=\"$node_query\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_thread_peek{node=\"$node_query\"}",
     "legendFormat": "peek"
    },
    {
     "expr": "jvm_thread{node=\"$node_query\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_thread_daemon{node=\"$node_query\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "JVM Compilation Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(jvm_compilation_time{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "compilation time"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_thread_NEW{node=\"$node_query\"}",
     "legendFormat": "NEW"
    },
    {
     "expr": "jvm_thread_RUNNABLE{node=\"$node_query\"}",
     "legendFormat": "RUNNABLE"
    },
    {
     "expr": "jvm_thread_BLOCKED{node=\"$node_query\"}",
     "legendFormat": "BLOCKED"
    },
    {
     "expr": "jvm_thread_WAITING{node=\"$node_query\"}",
     "legendFormat": "WAITING"
    },
    {
     "expr": "jvm_thread_TIMED_WAITING{node=\"$node_query\"}",
     "legendFormat": "TIMED_WAITING"
    },
    {
     "expr": "jvm_thread_TERMINATED{node=\"$node_query\"}",
     "legendFormat": "TERMINATED"
    }
   ]
  },
  { "title": "GC & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "JVM CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "p_cpu_load{node=\"$node_query\"}",
     "legendFormat": "cpu load"
    }
   ]
  },
  {
   "title": "JVM GC Used Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_time{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "{{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(jvm_gc_count{node=\"$node_query\"}[$__rate_interval]))",
     "legendFormat": "{{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_mem_heap_used{node=\"$node_query\"}",
     "legendFormat": "heap used"
    },
    {
     "expr": "jvm_mem_heap_committed{node=\"$node_query\"}",
     "legendFormat": "heap committed"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_mem_nonheap_used{node=\"$node_query\"}",
     "legendFormat": "non-heap used"
    },
    {
     "expr": "jvm_mem_nonheap_committed{node=\"$node_query\"}",
     "legendFormat": "non-heap committed"
    }
   ]
  },
  { "title": "Memory Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "JVM Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_mem_pool_used{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Over Times",
   "type": "timeseries",
   "description": "The number of times the JVM memory pool has used memory beyond the limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "jvm_mem_pool_over_count{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool GC Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_mem_pool_gc_used{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool GC Over Times",
   "type": "timeseries",
   "description": "The number of times the JVM memory pool used memory during GC exceeded the limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "jvm_mem_pool_gc_over_count{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  }
 ]
}