{
 "title": "Jvmm-Node Dashboard",
 "description": "Jvmm grafana dashboard for node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node_query", "label": "node", "query": { "query": "label_values(node)" } },
   { "name": "network_if_name", "label": "network interface", "query": { "query": "label_values(net_if_name)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_name}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_version}}"
    }
   ]
  },
  {
   "title": "OS Arch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_arch}}"
    }
   ]
  },
  {
   "title": "CPU Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_cpu{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU System Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_sys{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 10, "w": 21, "x": 3, "y": 5 } },
  {
   "title": "CPU Process Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_cpu_load{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_mem_used_present{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 } },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  { "gridPos": { "h": 8, "w": 3, "x": 0, "y": 33 } },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_file_used_present{node=\"$node_query\"}",
     "legendFormat": "{{file_name}}"
    }
   ]
  },
  {
   "title": "Disk IO (count/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "disk_read_speed{node=\"$node_query\"}",
     "legendFormat": "read: {{disk_name}}"
    },
    {
     "expr": "disk_write_speed{node=\"$node_query\"}",
     "legendFormat": "write: {{disk_name}}"
    }
   ]
  },
  {
   "title": "Disk Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "os_file_total{node=\"$node_query\"}",
     "legendFormat": "total {{file_name}}-{{file_label}}-{{file_type}}"
    },
    {
     "expr": "os_file_usable{node=\"$node_query\"}",
     "legendFormat": "usable {{file_name}}-{{file_label}}-{{file_type}}"
    }
   ]
  },
  {
   "title": "Disk IO (size/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_read_bytes_speed{node=\"$node_query\"}",
     "legendFormat": "{{disk_name}} read:"
    },
    {
     "expr": "disk_write_bytes_speed{node=\"$node_query\"}",
     "legendFormat": "{{disk_name}} write:"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Network State Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "net_conn_UNKNOWN{node=\"$node_query\"}",
     "legendFormat": "UNKNOWN"
    },
    {
     "expr": "net_conn_CLOSE{node=\"$node_query\"}",
     "legendFormat": "CLOSED"
    },
    {
     "expr": "net_conn_CLOSE_WAIT{node=\"$node_query\"}",
     "legendFormat": "CLOSE_WAIT"
    },
    {
     "expr": "net_conn_LISTEN{node=\"$node_query\"}",
     "legendFormat": "LISTEN"
    },
    {
     "expr": "net_conn_SYN_SENT{node=\"$node_query\"}",
     "legendFormat": "SYN_SENT"
    },
    {
     "expr": "net_conn_SYN_RECV{node=\"$node_query\"}",
     "legendFormat": "SYN_RECV"
    },
    {
     "expr": "net_conn_ESTABLISHED{node=\"$node_query\"}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "net_conn_FIN_WAIT_2{node=\"$node_query\"}",
     "legendFormat": "FIN_WAIT_2"
    },
    {
     "expr": "net_conn_FIN_WAIT_1{node=\"$node_query\"}",
     "legendFormat": "FIN_WAIT_1"
    },
    {
     "expr": "net_conn_CLOSING{node=\"$node_query\"}",
     "legendFormat": "CLOSING"
    },
    {
     "expr": "net_conn_LAST_ACK{node=\"$node_query\"}",
     "legendFormat": "LAST_ACK"
    },
    {
     "expr": "net_conn_TIME_WAIT{node=\"$node_query\"}",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "net_conn_NONE{node=\"$node_query\"}",
     "legendFormat": "NONE"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "net_conn{node=\"$node_query\"}",
     "legendFormat": "total:"
    },
    {
     "expr": "net_tcp4_conn{node=\"$node_query\"}",
     "legendFormat": "tcp4:"
    },
    {
     "expr": "net_tcp6_conn{node=\"$node_query\"}",
     "legendFormat": "tcp6:"
    },
    {
     "expr": "net_udp4_conn{node=\"$node_query\"}",
     "legendFormat": "udp4:"
    },
    {
     "expr": "net_udp6_conn{node=\"$node_query\"}",
     "legendFormat": "udp6:"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 } },
  { "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 } },
  {
   "title": "Network Interface IO (size/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "net_if_sent_speed{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} sent"
    },
    {
     "expr": "net_if_recv_speed{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} recv"
    }
   ]
  }
 ]
}