{
 "title": "Jvmm Dashboard",
 "description": "Jvmm grafana dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node_query", "label": "node", "query": { "query": "label_values(node)" } },
   { "name": "network_if_name", "label": "network interface", "query": { "query": "label_values(net_if_name)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_name}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_version}}"
    }
   ]
  },
  {
   "title": "OS Arch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_arch}}"
    }
   ]
  },
  {
   "title": "CPU Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_cpu{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 } },
  { "gridPos": { "h": 10, "w": 21, "x": 3, "y": 5 } },
  { "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 } },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_mem_used_present{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 } },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  { "gridPos": { "h": 8, "w": 3, "x": 0, "y": 33 } },
  { "gridPos": { "h": 8, "w": 9, "x": 3, "y": 33 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 } },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 } },
  { "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 } },
  { "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 } },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  { "gridPos": { "h": 4, "w": 4, "x": 0, "y": 67 } },
  { "gridPos": { "h": 8, "w": 3, "x": 4, "y": 67 } },
  {
   "title": "JVM Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 67 },
   "targets": [
    {
     "expr": "jvm_loaded_class_total{node=\"$node_query\"}",
     "legendFormat": "total loaded class"
    },
    {
     "expr": "jvm_loaded_class{node=\"$node_query\"}",
     "legendFormat": "loaded class"
    },
    {
     "expr": "jvm_unloaded_class{node=\"$node_query\"}",
     "legendFormat": "unloaded class"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 } },
  { "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 } },
  { "gridPos": { "h": 8, "w": 7, "x": 0, "y": 75 } },
  { "gridPos": { "h": 8, "w": 9, "x": 7, "y": 75 } },
  { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 } },
  { "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 } },
  { "title": "JVM Memory Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 } }
 ]
}