{
 "title": "Jvmm-JVM Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_query", "label": "node", "query": { "query": "label_values(node)" } },
   { "name": "network_if_name", "label": "network interface", "query": { "query": "label_values(net_if_name)" } }
  ]
 },
 "panels": [
  {
   "title": "JVM Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_mem_heap_used_present{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "jvm_loaded_class_total{node=\"$node_query\"}",
     "legendFormat": "total loaded class"
    },
    {
     "expr": "jvm_loaded_class{node=\"$node_query\"}",
     "legendFormat": "loaded class"
    },
    {
     "expr": "jvm_unloaded_class{node=\"$node_query\"}",
     "legendFormat": "unloaded class"
    }
   ]
  },
  {
   "title": "Compilation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_compilation_time{node=\"$node_query\"}",
     "legendFormat": "compilation time"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "{{vm_version}}"
    }
   ]
  },
  {
   "title": "JVM Pending Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_mem_pending{node=\"$node_query\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "jvm_thread_locked{node=\"$node_query\"}",
     "legendFormat": "locked"
    },
    {
     "expr": "jvm_thread_peek{node=\"$node_query\"}",
     "legendFormat": "peek"
    },
    {
     "expr": "jvm_thread{node=\"$node_query\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_thread_daemon{node=\"$node_query\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "jvm_thread_NEW{node=\"$node_query\"}",
     "legendFormat": "NEW"
    },
    {
     "expr": "jvm_thread_RUNNABLE{node=\"$node_query\"}",
     "legendFormat": "RUNNABLE"
    },
    {
     "expr": "jvm_thread_BLOCKED{node=\"$node_query\"}",
     "legendFormat": "BLOCKED"
    },
    {
     "expr": "jvm_thread_WAITING{node=\"$node_query\"}",
     "legendFormat": "WAITING"
    },
    {
     "expr": "jvm_thread_TIMED_WAITING{node=\"$node_query\"}",
     "legendFormat": "TIMED_WAITING"
    },
    {
     "expr": "jvm_thread_TERMINATED{node=\"$node_query\"}",
     "legendFormat": "TERMINATED"
    }
   ]
  },
  {
   "title": "JVM GC Used Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_time{node=\"$node_query\"}[$__rate_interval])",
     "legendFormat": "{{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(jvm_gc_count{node=\"$node_query\"}[$__rate_interval]))",
     "legendFormat": "{{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_mem_heap_used{node=\"$node_query\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_mem_nonheap_used{node=\"$node_query\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_mem_pool_used{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Over Times",
   "type": "timeseries",
   "description": "The number of times the JVM memory pool has used memory beyond the limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "jvm_mem_pool_over_count{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool GC Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_mem_pool_gc_used{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool GC Over Times",
   "type": "timeseries",
   "description": "The number of times the JVM memory pool used memory during GC exceeded the limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "jvm_mem_pool_gc_over_count{node=\"$node_query\"}",
     "legendFormat": "{{jvm_mem_pool_name}}({{jvm_mem_pool_type}})"
    }
   ]
  }
 ]
}