{
 "title": "Jvmm-Node Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_query", "label": "node", "query": { "query": "label_values(node)" } },
   { "name": "network_if_name", "label": "network interface", "query": { "query": "label_values(net_if_name)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_name}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_version}}"
    }
   ]
  },
  {
   "title": "OS Arch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_arch}}"
    }
   ]
  },
  {
   "title": "Process Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p_up_time{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_load_avg{node=\"$node_query\"}",
     "legendFormat": "{{os_name}}-{{os_version}}-{{os_arch}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Num",
   "type": "stat",
   "gridPos": { "h": 10, "w": 1, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_cpu{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_sys{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cpu_sys{node=\"$node_query\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_user{node=\"$node_query\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_io_wait{node=\"$node_query\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU User Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_user{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_mem_used_present{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "os_mem_total{node=\"$node_query\"}",
     "legendFormat": "total"
    },
    {
     "expr": "os_mem_committed{node=\"$node_query\"}",
     "legendFormat": "committed"
    },
    { "expr": "os_mem_free", "legendFormat": "free" }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "os_mem_total_swap{node=\"$node_query\"}",
     "legendFormat": "total"
    },
    {
     "expr": "os_mem_free_swap{node=\"$node_query\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Buffer Cache & Shared Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "os_mem_buffer_cache{node=\"$node_query\"}",
     "legendFormat": "buffer cache"
    },
    { "expr": "os_mem_shared", "legendFormat": "shared" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk Used (ALL)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_file_all_used_present{node=\"$node_query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_file_used_present{node=\"$node_query\"}",
     "legendFormat": "{{file_name}}"
    }
   ]
  },
  {
   "title": "Disk IO (count/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "disk_read_speed{node=\"$node_query\"}",
     "legendFormat": "read: {{disk_name}}"
    },
    {
     "expr": "disk_write_speed{node=\"$node_query\"}",
     "legendFormat": "write: {{disk_name}}"
    }
   ]
  },
  {
   "title": "Disk Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "os_file_total{node=\"$node_query\"}",
     "legendFormat": "total {{file_name}}-{{file_label}}-{{file_type}}"
    },
    {
     "expr": "os_file_usable{node=\"$node_query\"}",
     "legendFormat": "usable {{file_name}}-{{file_label}}-{{file_type}}"
    }
   ]
  },
  {
   "title": "Disk IO (size/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_read_bytes_speed{node=\"$node_query\"}",
     "legendFormat": "{{disk_name}} read:"
    },
    {
     "expr": "disk_write_bytes_speed{node=\"$node_query\"}",
     "legendFormat": "{{disk_name}} write:"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Network State Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "net_conn_UNKNOWN{node=\"$node_query\"}",
     "legendFormat": "UNKNOWN"
    },
    {
     "expr": "net_conn_CLOSE{node=\"$node_query\"}",
     "legendFormat": "CLOSED"
    },
    {
     "expr": "net_conn_CLOSE_WAIT{node=\"$node_query\"}",
     "legendFormat": "CLOSE_WAIT"
    },
    {
     "expr": "net_conn_LISTEN{node=\"$node_query\"}",
     "legendFormat": "LISTEN"
    },
    {
     "expr": "net_conn_SYN_SENT{node=\"$node_query\"}",
     "legendFormat": "SYN_SENT"
    },
    {
     "expr": "net_conn_SYN_RECV{node=\"$node_query\"}",
     "legendFormat": "SYN_RECV"
    },
    {
     "expr": "net_conn_ESTABLISHED{node=\"$node_query\"}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "net_conn_FIN_WAIT_2{node=\"$node_query\"}",
     "legendFormat": "FIN_WAIT_2"
    },
    {
     "expr": "net_conn_FIN_WAIT_1{node=\"$node_query\"}",
     "legendFormat": "FIN_WAIT_1"
    },
    {
     "expr": "net_conn_CLOSING{node=\"$node_query\"}",
     "legendFormat": "CLOSING"
    },
    {
     "expr": "net_conn_LAST_ACK{node=\"$node_query\"}",
     "legendFormat": "LAST_ACK"
    },
    {
     "expr": "net_conn_TIME_WAIT{node=\"$node_query\"}",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "net_conn_NONE{node=\"$node_query\"}",
     "legendFormat": "NONE"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "net_conn{node=\"$node_query\"}",
     "legendFormat": "total:"
    },
    {
     "expr": "net_tcp4_conn{node=\"$node_query\"}",
     "legendFormat": "tcp4:"
    },
    {
     "expr": "net_tcp6_conn{node=\"$node_query\"}",
     "legendFormat": "tcp6:"
    },
    {
     "expr": "net_udp4_conn{node=\"$node_query\"}",
     "legendFormat": "udp4:"
    },
    {
     "expr": "net_udp6_conn{node=\"$node_query\"}",
     "legendFormat": "udp6:"
    }
   ]
  },
  {
   "title": "Network Interface IO (Total Size)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "net_if_sent_bytes{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} sent"
    },
    {
     "expr": "net_if_recv_bytes{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} recv"
    }
   ]
  },
  {
   "title": "Network Interface IO (Total Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "net_if_sent_count{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} sent"
    },
    {
     "expr": "net_if_recv_count{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} recv"
    }
   ]
  },
  {
   "title": "Network Interface IO (size/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "net_if_sent_speed{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} sent"
    },
    {
     "expr": "net_if_recv_speed{node=\"$node_query\", net_if_name=\"$network_if_name\"}",
     "legendFormat": "{{net_if_name}}-{{net_if_alias}} recv"
    }
   ]
  }
 ]
}