package org.beifengtz.jvmm.convey.enums;

/**
 * <p>
 * Description: TODO
 * </p>
 * <p>
 * Created in 8:42 下午 2021/5/17
 *
 * @author beifengtz
 */
public enum GlobalType {
    /**
     * 默认协议
     */
    JVMM_TYPE_HANDLE_MSG,
    /**
     * 心跳包
     */
    JVMM_TYPE_HEARTBEAT,
    /**
     * 安全认证
     */
    JVMM_TYPE_BUBBLE,
    JVMM_TYPE_AUTHENTICATION,
    /**
     * ping pong联通测试，服务发现也可用此协议
     */
    JVMM_TYPE_PING,
    JVMM_TYPE_PONG,

    /**
     * 关闭目标Jvmm服务器（并不是宿主服务）
     */
    JVMM_TYPE_SERVER_SHUTDOWN,

    /**
     * 执行类协议
     */
    JVMM_TYPE_EXECUTE_GC,
    JVMM_TYPE_EXECUTE_SET_CLASSLOADING_VERBOSE,
    JVMM_TYPE_EXECUTE_SET_MEMORY_VERBOSE,
    JVMM_TYPE_EXECUTE_SET_THREAD_CPU_TIME_ENABLED,
    JVMM_TYPE_EXECUTE_SET_THREAD_CONTENTION_MONITOR_ENABLED,
    JVMM_TYPE_EXECUTE_RESET_PEAK_THREAD_COUNT,
    JVMM_TYPE_EXECUTE_JAVA_PROCESS,
    JVMM_TYPE_EXECUTE_JVM_TOOL,
    JVMM_TYPE_EXECUTE_JAD,
    JVMM_TYPE_EXECUTE_LOAD_PATCH,

    /**
     * 信息采集类协议
     */
    JVMM_TYPE_COLLECT_SYS_INFO,
    JVMM_TYPE_COLLECT_PROCESS_INFO,
    JVMM_TYPE_COLLECT_CPU_INFO,
    JVMM_TYPE_COLLECT_NETWORK_INFO,
    JVMM_TYPE_COLLECT_SYS_MEMORY_INFO,
    JVMM_TYPE_COLLECT_DISK_INFO,
    JVMM_TYPE_COLLECT_DISK_IO_INFO,
    JVMM_TYPE_COLLECT_SYS_FILE_INFO,
    JVMM_TYPE_COLLECT_PORT_STATUS,
    JVMM_TYPE_COLLECT_JVM_CLASSLOADING_INFO,
    JVMM_TYPE_COLLECT_JVM_CLASSLOADER_INFO,
    JVMM_TYPE_COLLECT_JVM_COMPILATION_INFO,
    JVMM_TYPE_COLLECT_JVM_GC_INFO,
    JVMM_TYPE_COLLECT_JVM_MEMORY_MANAGER_INFO,
    JVMM_TYPE_COLLECT_JVM_MEMORY_POOL_INFO,
    JVMM_TYPE_COLLECT_JVM_MEMORY_INFO,
    JVMM_TYPE_COLLECT_JVM_THREAD_STACK,
    JVMM_TYPE_COLLECT_JVM_THREAD_INFO,
    JVMM_TYPE_COLLECT_JVM_THREAD_DETAIL,
    JVMM_TYPE_COLLECT_JVM_DUMP_THREAD,
    JVMM_TYPE_COLLECT_JVM_THREAD_POOL,

    /**
     * Web端批量采集
     */
    JVMM_TYPE_COLLECT_BATCH,

    /**
     * async-profiler数据采样相关协议
     */
    JVMM_TYPE_PROFILER_EXECUTE,
    JVMM_TYPE_PROFILER_SAMPLE,
    JVMM_TYPE_PROFILER_SAMPLE_START,
    JVMM_TYPE_PROFILER_SAMPLE_STOP,
    JVMM_TYPE_PROFILER_STATUS,
    JVMM_TYPE_PROFILER_LIST_EVENTS,
}
